apiVersion: "db.orange.com/v1alpha1"
kind: "CassandraCluster"
metadata:
  name: cassandra-demo
  labels:
    cluster: katacoda
spec:
  baseImage: orangeopensource/cassandra-image
  version: 3.11.4-8u212-0.3.1-cqlsh
  configMapName: cassandra-configmap-v1
  dataCapacity: "1Gi"
  dataStorageClass: "local-storage"
  imagepullpolicy: IfNotPresent  
  checkStatefulsetsAreEqual: true
  hardAntiAffinity: false           # Do we ensure only 1 cassandra on each node ?
  deletePVC: true
  autoPilot: false
  gcStdout: true
  autoUpdateSeedList: false
  maxPodUnavailable: 1
  runAsUser: 1000
  resources:         
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: 500m
      memory: 1Gi
  topology:
    dc:
      - name: dc1
        nodesPerRacks: 1
        rack:
          - name: rack1
          - name: rack2
          - name: rack3
